server:
  port: 1300
spring:
  application:
    name: sms

  datasource:
    url: jdbc:mysql://localhost/sms
    username: root
    password: root2004

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
